module.exports = {
  apps: [
    {
      name: 'fb-api',
      script: 'apps/api/dist/main.js',
      cwd: '/home/funbreak/funbreakseo',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 4000,
      },
      error_file: '/home/funbreak/funbreakseo/logs/api-error.log',
      out_file: '/home/funbreak/funbreakseo/logs/api-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      max_memory_restart: '1G',
      restart_delay: 3000,
      max_restarts: 10,
    },
    {
      name: 'fb-web',
      script: 'node_modules/.bin/next',
      args: 'start --port 3000',
      cwd: '/home/funbreak/funbreakseo/apps/web',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
        NEXT_PUBLIC_API_URL: 'https://api.funbreakseo.com/api/v1',
      },
      error_file: '/home/funbreak/funbreakseo/logs/web-error.log',
      out_file: '/home/funbreak/funbreakseo/logs/web-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      max_memory_restart: '1G',
      restart_delay: 3000,
      max_restarts: 10,
    },
    {
      name: 'fb-admin',
      script: 'node_modules/.bin/next',
      args: 'start --port 3001',
      cwd: '/home/funbreak/funbreakseo/apps/admin',
      env: {
        NODE_ENV: 'production',
        PORT: 3001,
        NEXT_PUBLIC_API_URL: 'https://api.funbreakseo.com/api/v1',
      },
      error_file: '/home/funbreak/funbreakseo/logs/admin-error.log',
      out_file: '/home/funbreak/funbreakseo/logs/admin-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      max_memory_restart: '1G',
      restart_delay: 3000,
      max_restarts: 10,
    },
  ],
};
