module.exports = {
  apps: [
    {
      name: 'fb-api',
      script: 'apps/api/dist/main.js',
      instances: 1,
      exec_mode: 'cluster',
      env: { NODE_ENV: 'production', PORT: 4000 },
      error_file: './logs/api-error.log',
      out_file: './logs/api-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      max_memory_restart: '1G',
    },
    {
      name: 'fb-worker',
      script: 'node',
      args: '-r tsconfig-paths/register apps/api/dist/worker.js',
      env: { NODE_ENV: 'production' },
      error_file: './logs/worker-error.log',
      out_file: './logs/worker-out.log',
      max_memory_restart: '2G',
    },
    {
      name: 'fb-web',
      script: 'node_modules/.bin/next',
      args: 'start',
      cwd: './apps/web',
      env: { NODE_ENV: 'production', PORT: 3000 },
      error_file: '../../logs/web-error.log',
      out_file: '../../logs/web-out.log',
    },
    {
      name: 'fb-admin',
      script: 'node_modules/.bin/next',
      args: 'start',
      cwd: './apps/admin',
      env: { NODE_ENV: 'production', PORT: 3001 },
      error_file: '../../logs/admin-error.log',
      out_file: '../../logs/admin-out.log',
    },
  ],
};
